# Generated by Django 5.2.1 on 2025-06-03 11:43

import django.db.models.deletion
import media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, storage=media_utils.LocalMediaStorage(), upload_to='post_media/')),
                ('file_sm', models.URLField(blank=True, null=True)),
                ('file_md', models.URLField(blank=True, null=True)),
                ('file_lg', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post')),
            ],
            bases=(models.Model, media_utils.ImageVariantMixin),
        ),
    ]
