# Generated by Copilot for tag support
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0007_postlike_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('popularity', models.PositiveIntegerField(default=0, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Tag'),
        ),
    ]
