# Generated by Django 5.2.1 on 2025-06-03 11:24

import media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_avatar_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=media_utils.LocalMediaStorage(), upload_to='avatars/'),
        ),
    ]
