# Black configuration
[tool.black]
line-length = 88
target-version = ['py313']
include = '\.pyi?$'
exclude = '''
/(
    \..*|  # hidden directories
    venv|
    env|
    __pycache__|
    migrations|
    media
)/
'''

# isort configuration
[tool.isort]
profile = "black"
line_length = 88
skip = ["venv", "env", "migrations", "media"]
