# Generated by Django 5.2.1 on 2025-06-03 22:00

import media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=media_utils.LocalMediaStorage(), upload_to='messages/images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, storage=media_utils.LocalMediaStorage(), upload_to='messages/videos/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
